### ISSUE TITLE
v0.0.9.3 does not support version 2.0 key files

### ISSUE THREAD

**Issue by ReneSchumacher** [JustinGrote/SecretManagement.KeePass#16]
I've been trying to use the module with a KeePass database secured by a key file with format version 2.0 as recommended by KeePass v2.47. The module fails to connect to the database stating that the composite key is invalid. Switching to format version 1.0 for the key file works.

**Comment by JustinGrote** [comment]
Hi @ReneSchumacher, thanks for reporting.

Since that new file format is very new in 2.47, my downstream library I'm using for cross-platform (pt.keepasslib) hasn't reached that version yet, so this is currently unsupported.

https://github.com/panteam-net/pt.KeePassLibStd/discussions/8

I'll leave this issue open until a 2.47 .NET standard library is available to upgrade to.

**Comment by ReneSchumacher** [comment]
Hey,

that's what I thought. Just wanted to let you know. Switching to 1.0 format is an easy workaround.

**Comment by JustinGrote** [comment]
@ReneSchumacher if there's an extended period before the new library gets released maybe I'll add a quick check to look for the new format and throw a warning.

**Comment by JustinGrote** [comment]
This is no longer blocked: https://github.com/panteam-net/pt.KeePassLibStd/discussions/8#discussioncomment-390719

I will try to add the feature in the next couple days.

**Comment by JustinGrote** [comment]
@ReneSchumacher Keyfile v2 support should be in 0.0.9.4
