### ISSUE TITLE
Add Microsoft.PowerShell.SecretManagement Module dependency to Module Manifest

### ISSUE THREAD

**Issue by stefanstranger** [JustinGrote/SecretManagement.KeePass#3]
Hi Justin,

Would it be an idea to add the Microsoft.PowerShell.SecretManagement PowerShell module to RequiredModules attribute in the Module manifest file?

Stefan

**Comment by JustinGrote** [comment]
@stefanstranger good idea! I assumed if you were installing this module that would have been a given, but no reason not to make it explicit.

**Comment by bjompen** [comment]
Hi.

It seems this causes problems when installing the module.
I assume it's because the Microsoft.PowerShell.SecretManagement is in AllowPrerelease it can't be found and Install/Save-Module fails when trying to get this module.

![image](https://user-images.githubusercontent.com/17783007/96698046-f31c4f00-138c-11eb-8a90-6c7c4e0f4dbb.png)

**Comment by JustinGrote** [comment]
@bjompen thanks but I think I'm going to leave it as is for when secretmanagement leaves prerelease. I'm going to recommend the workaround for now of:

Install-Module SecretManagement.KeePass,Microsoft.Powershell.SecretManagement

**Comment by bjompen** [comment]
Thats ok.
The workaround doesn't seem to work in PSGet2 either though.
Instead, I'd suggest just downloading the repo and manually placing it in the `$env:PSModulePath` (or registering from source) somewhere as a workaround.
