### ISSUE TITLE
Unlock SecretManagement.KeePass in a script

### ISSUE THREAD

**Issue by user8446** [JustinGrote/SecretManagement.KeePass#35]
Hello,

Currently you are unable to use the module in a script (non-interactively). Is it on the roadmap to be able to unlock in scripts? (for example: `Unlock-KeePassVault -Password $password`).

This is similar issue to: https://github.com/PowerShell/SecretStore/issues/46

Thank you for the talent put into this!

**Comment by JustinGrote** [comment]
@user8446 There are no plans to support "master key" files in this approach, because then where would you store the master key? Completely defeats the purpose of the secret store.

Instead, for the scripted approach, it is recommended that you use a keyfile-only Keepass vault, and supply the keyfile, either from a protected removable physical medium such as a USB drive, or retrieved from something like Azure Key Vault.

I may consider storing the password in Credential Manager (DPAPI), but I have a completely separate vault for that purpose already, might as well keep the secrets there.

**Comment by JustinGrote** [comment]
@user8446 I'll consider adding it and throwing a warning every time :)

**Comment by JustinGrote** [comment]
Per the discussion in the other thread, I will add a Unlock-KeePassSecretVault command that will persist the entered master password as a secure string within the module scope, and will persist until the module is reloaded.

**Comment by user8446** [comment]
That's great and I'm looking forward to testing when ready. I was going to send you a coffee but didn't find a link.... ☕

**Comment by JustinGrote** [comment]
@user8446 you can donate to OTAT :)
https://www.facebook.com/otatpdx/

**Comment by user8446** [comment]
Good cause and done :)
