### ISSUE TITLE
Not working in PWSH 7

### ISSUE THREAD

**Issue by Callidus2000** [JustinGrote/SecretManagement.KeePass#57]
The module is not working under Powershell 7, which is a known bug/limitation in the underlying PoSHKeepass module. Maybe a switch to the [ModernKeePassLib](https://www.nuget.org/packages/ModernKeePassLib/) would be a solution...

**Comment by JustinGrote** [comment]
@Callidus2000 ModernKeePassLib hasn't been updated since 2020 so it doesn't have key features like the new key format. My PoshKeePass is heavily modified from the original.

It's been working fine for me in PS7 but I haven't tested lately, do you have a specific error message or stacktrace rather than "it's no working?" :)

**Comment by Callidus2000** [comment]
Sorry, please ignore the issue. Somehow my session was corrupt, in a fresh pwsh session the error does not occure.

That was the error message I got:
```
Vault testVault: Exception calling ".ctor" with "1" argument(s):
"Could not load type 'System.Security.Cryptography.ProtectedMemory‘
from assembly 'System.Security, Version=4.0.0.0,Culture=neutral, PublicKeyToken=b03f5f7flld50a3a'."
```
![image](https://user-images.githubusercontent.com/73584079/125465155-5a1c87d7-bd36-4610-8508-60a4d99ea61a.png)

**Comment by Callidus2000** [comment]
Thanks for the information.. The fun never stops ;-)
